[project]
name = "regulatory"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Satyapriya", email = "satyapriya.satyajit@merai.co" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
regulatory = "regulatory:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
